name: Validate Markdown Links

on: [pull_request]

permissions:
  contents: read
  issues: write

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if token works
        run: |
          echo "Testing GITHUB_TOKEN..."
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user
        shell: bash

      - name: Run Markdown Link Validator
        uses: ./.github/actions/markdown-link-validator
