name: Validate Markdown Links

on: [pull_request]

permissions:
  contents: read
  issues: write

jobs:
  debug-token:
    runs-on: ubuntu-latest
    steps:
      - name: Check token permissions
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission


  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Markdown Link Validator
        uses: ./.github/actions/markdown-link-validator
        with:
          token: ${{ secrets.GITHUB_TOKEN }}


  check-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Markdown Linter and Style Checker
        uses: ./.github/actions/markdown-lint-stylecheck
